name: wendys_challenge
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  go_router: ^14.8.1
  google_fonts: ^6.2.1
  json_annotation: ^4.9.0
  loader_overlay: ^5.0.0
  loading_animation_widget: ^1.3.0
  mocktail: ^1.0.4
  shared_preferences: ^2.5.3

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.4
  json_serializable: ^6.9.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
