name: Flutter CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Run Flutter CI Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter (latest stable)
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
          key: ${{ runner.os }}-pub-cache-${{ hashFiles('**/pubspec.yaml') }}

      - name: Install dependencies
        run: flutter pub get

      - name: Generate files from build_runner
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Run analysis
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Build APK (Debug)
        # just a dummy step to show the build step
        # This step is not necessary for the CI pipeline but can be used to build the APK
        run: |
          flutter build apk --debug
          echo "APK built successfully!"